-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Harjoitus CASCADE;
DROP TABLE IF EXISTS Rasti CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS Ammunta CASCADE;
DROP TABLE IF EXISTS KayttajanHarjoitus CASCADE;

